#!/bin/bash
# Script: render-nginx-site.sh
# Purpose: A config written with an unquoted heredoc and an unset variable ships "server_name ;" and a reload that fails at 2 a.m. — this renders the file with set -u, writes it atomically and checks it before it replaces anything.
# Usage: DOMAIN=example.com PORT=3000 ./render-nginx-site.sh OUTPUT_FILE
set -euo pipefail

CHECK="✓"
CROSS="✗"

[[ $# -eq 1 ]] || { echo "usage: DOMAIN=... PORT=... $0 OUTPUT_FILE" >&2; exit 2; }
OUT="$1"
# :? stops here with a named error instead of rendering an empty value into the file.
: "${DOMAIN:?set DOMAIN, e.g. DOMAIN=example.com}"
: "${PORT:?set PORT, e.g. PORT=3000}"
[[ "$PORT" =~ ^[0-9]+$ ]] || { echo "$CROSS PORT must be a number, got: $PORT" >&2; exit 2; }

# Same directory as the target, so the final mv is an atomic rename, never a half-written file.
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

# Unquoted EOF: ${DOMAIN} and ${PORT} expand now. nginx's own variables are escaped (\$host) so they reach the file as written.
cat > "$TMP" <<EOF
# generated by render-nginx-site.sh: edit the script, not this file
server {
    listen 80;
    server_name ${DOMAIN} www.${DOMAIN};

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}
EOF

# Any other $name left in the output is a variable that should have been set or escaped.
# shellcheck disable=SC2016  # the $ in these patterns is a literal dollar sign, on purpose
if grep -noE '\$\{?[A-Za-z_]+' "$TMP" | grep -vE ':\$(host|proxy_add_x_forwarded_for)$'; then
  echo "$CROSS unexpected \$variable left in the output (lines above)" >&2
  exit 1
fi

mv -- "$TMP" "$OUT"
trap - EXIT
echo "$CHECK wrote $OUT for $DOMAIN -> 127.0.0.1:$PORT"
